#!/bin/bash


rest=http://127.0.0.1:9200

function pretty() {
	curl "$rest/?pretty"
}

function _shutdown() {
	curl -XPOST "$rest/_shutdown"
}

function count() {
	curl -XGET "$rest/_count?pretty" -d '
{
  "query": {
    "match_all": {}
  }
}
'
}

function match_all() {
	curl -XGET "$rest/bz1?pretty" -d '
{
  "match_all": {}
}
'
}

function search_all() {
	curl -XGET "$rest/_search?pretty" -d '
{
  "query": {
    "match_all": {}
  }
}
'
}



$1
