package req
// Generated by genfront -- do not edit this file.

const (
    OPTIONS = "OPTIONS"
    GET = "GET"
    HEAD = "HEAD"
    POST = "POST"
    PUT = "PUT"
    DELETE = "DELETE"
    TRACE = "TRACE"
    CONNECT = "CONNECT"
)

// Methods for the Rest state
func (r *Rest) Options() *Rest {
    return r.Method(OPTIONS)
}
func (r *Rest) Get() *Rest {
    return r.Method(GET)
}
func (r *Rest) Head() *Rest {
    return r.Method(HEAD)
}
func (r *Rest) Post() *Rest {
    return r.Method(POST)
}
func (r *Rest) Put() *Rest {
    return r.Method(PUT)
}
func (r *Rest) Delete() *Rest {
    return r.Method(DELETE)
}
func (r *Rest) Trace() *Rest {
    return r.Method(TRACE)
}
func (r *Rest) Connect() *Rest {
    return r.Method(CONNECT)
}